<?php

require_once(dirname(__FILE__) . '/IftRunner.module'); 

class IftActionHello extends IftActionModule implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Hello World (Ift Action)', 
			'summary' => 'An example if an action that produces a "Hello World" message when you save a page.', 
			'version' => 1, 
			'author' => 'Avoine and ProcessWire', 
			'requires' => 'IftRunner',
			); 
	}

	public function __construct() {
		$this->set('helloMessage', 'Hello World!'); 
	}

	public function ___action($item) { 

		$message = "<pre style='line-height: 1em; font-family: monospace'>
 _          _ _                            _     _ 
| |        | | |                          | |   | |
| |__   ___| | | ___   __      _____  _ __| | __| |
| '_ \ / _ \ | |/ _ \  \ \ /\ / / _ \| '__| |/ _` |
| | | |  __/ | | (_) |  \ V  V / (_) | |  | | (_| |
|_| |_|\___|_|_|\___/    \_/\_/ \___/|_|  |_|\__,_|
</pre>";

		$message .= "<br /><b>" . $this->wire('sanitizer')->entities($this->helloMessage) . "</b>"; 
		$message .= "<br />" . $item->path; 
		$this->message($message, Notice::allowMarkup); 
		return true; 
	}

	public function ___getConfigInputfields() {
		$fieldset = parent::___getConfigInputfields();
		$f = $this->wire('modules')->get('InputfieldText'); 
		$f->attr('name', 'helloMessage'); 
		$f->attr('value', $this->helloMessage); 
		$f->label = $this->_('Custom Hello Message'); 
		$f->description = $this->_('This message will be displayed whenever the action is run.'); 
		$fieldset->add($f); 
		return $fieldset; 
	}
}


